export const REQUIRED_COLUMNS = [
  'Employee_Name',
  'Role',
  'Reports_To',
  'Mentor_Name',
  'Client',
  'Project_Type',
  'Smartest_V7',
  'Smartest_V8',
  'Test_Program_Integration',
  'Test_Program_Development',
  'Pattern_Debugs',
  'Scripting_Tools',
  'Data_Analytics',
  'Version_Control_Git',
  'IP_Knowledge',
  'Post_Silicon_Validation',
  'Bench_Setup_Stabilization',
  'Loadboard_Bringup',
  'HW_Validation',
  'GRR_Analysis',
  'Engineering_Bringups',
  'Multisite_Bringup',
  'TapeOut_To_HVM',
  'Volume_KPI_Analysis',
  'Production_Release_Track',
  'Is_Independent',
  'Does_Automation_Scripting',
  'Handles_1_on_1_Mentoring',
  'Produces_Documentation',
  'Runs_Classroom_Training',
  'Manages_Project_Deliverables',
  'Manages_Multiple_Clients',
]

export const SKILL_COLUMNS = [
  'Smartest_V7',
  'Smartest_V8',
  'Test_Program_Integration',
  'Test_Program_Development',
  'Pattern_Debugs',
  'Scripting_Tools',
  'Data_Analytics',
  'Version_Control_Git',
  'IP_Knowledge',
  'Post_Silicon_Validation',
  'Bench_Setup_Stabilization',
  'Loadboard_Bringup',
  'HW_Validation',
  'GRR_Analysis',
  'Engineering_Bringups',
  'Multisite_Bringup',
  'TapeOut_To_HVM',
  'Volume_KPI_Analysis',
  'Production_Release_Track',
]

export const LAB_SKILL_COLUMNS = [
  'Bench_Setup_Stabilization',
  'Loadboard_Bringup',
  'GRR_Analysis',
  'Post_Silicon_Validation',
]

export const PROCESS_SKILL_COLUMNS = [
  'Test_Program_Integration',
  'Test_Program_Development',
  'Pattern_Debugs',
  'Scripting_Tools',
  'Data_Analytics',
  'Version_Control_Git',
  'IP_Knowledge',
  'HW_Validation',
  'Engineering_Bringups',
  'Multisite_Bringup',
  'TapeOut_To_HVM',
  'Volume_KPI_Analysis',
  'Production_Release_Track',
]

export const BOOLEAN_COLUMNS = [
  'Is_Independent',
  'Does_Automation_Scripting',
  'Handles_1_on_1_Mentoring',
  'Produces_Documentation',
  'Runs_Classroom_Training',
  'Manages_Project_Deliverables',
  'Manages_Multiple_Clients',
]

export const META_COLUMNS = [
  'Employee_Name',
  'Role',
  'Reports_To',
  'Mentor_Name',
  'Client',
  'Project_Type',
]
