import Papa from 'papaparse'
import { REQUIRED_COLUMNS } from './csvSchema'

const SAMPLE_ROWS = [
  {
    Employee_Name: 'Priya Nair',
    Role: 'Manager',
    Reports_To: '',
    Mentor_Name: '',
    Client: 'Qualcomm',
    Project_Type: 'HVM Support',
    Smartest_V7: 8, Smartest_V8: 9,
    Test_Program_Integration: 8, Test_Program_Development: 8, Pattern_Debugs: 7,
    Scripting_Tools: 8, Data_Analytics: 8, Version_Control_Git: 9, IP_Knowledge: 8,
    Post_Silicon_Validation: 7, Bench_Setup_Stabilization: 7, Loadboard_Bringup: 7,
    HW_Validation: 8, GRR_Analysis: 7,
    Engineering_Bringups: 8, Multisite_Bringup: 8, TapeOut_To_HVM: 9,
    Volume_KPI_Analysis: 9, Production_Release_Track: 9,
    Is_Independent: true, Does_Automation_Scripting: true, Handles_1_on_1_Mentoring: true,
    Produces_Documentation: true, Runs_Classroom_Training: true,
    Manages_Project_Deliverables: true, Manages_Multiple_Clients: true,
  },
  {
    Employee_Name: 'Arjun Mehta',
    Role: 'Sr Lead',
    Reports_To: 'Priya Nair',
    Mentor_Name: 'Priya Nair',
    Client: 'Qualcomm',
    Project_Type: 'New Product Intro',
    Smartest_V7: 9, Smartest_V8: 9,
    Test_Program_Integration: 9, Test_Program_Development: 9, Pattern_Debugs: 8,
    Scripting_Tools: 9, Data_Analytics: 8, Version_Control_Git: 9, IP_Knowledge: 8,
    Post_Silicon_Validation: 8, Bench_Setup_Stabilization: 8, Loadboard_Bringup: 9,
    HW_Validation: 8, GRR_Analysis: 8,
    Engineering_Bringups: 9, Multisite_Bringup: 9, TapeOut_To_HVM: 9,
    Volume_KPI_Analysis: 8, Production_Release_Track: 9,
    Is_Independent: true, Does_Automation_Scripting: true, Handles_1_on_1_Mentoring: true,
    Produces_Documentation: true, Runs_Classroom_Training: true,
    Manages_Project_Deliverables: true, Manages_Multiple_Clients: true,
  },
  {
    Employee_Name: 'Sneha Reddy',
    Role: 'Lead',
    Reports_To: 'Arjun Mehta',
    Mentor_Name: 'Arjun Mehta',
    Client: 'Qualcomm',
    Project_Type: 'Characterization',
    Smartest_V7: 8, Smartest_V8: 8,
    Test_Program_Integration: 8, Test_Program_Development: 8, Pattern_Debugs: 8,
    Scripting_Tools: 8, Data_Analytics: 7, Version_Control_Git: 8, IP_Knowledge: 7,
    Post_Silicon_Validation: 8, Bench_Setup_Stabilization: 8, Loadboard_Bringup: 8,
    HW_Validation: 7, GRR_Analysis: 8,
    Engineering_Bringups: 8, Multisite_Bringup: 8, TapeOut_To_HVM: 8,
    Volume_KPI_Analysis: 7, Production_Release_Track: 8,
    Is_Independent: true, Does_Automation_Scripting: true, Handles_1_on_1_Mentoring: true,
    Produces_Documentation: true, Runs_Classroom_Training: false,
    Manages_Project_Deliverables: true, Manages_Multiple_Clients: false,
  },
  {
    Employee_Name: 'Karthik Iyer',
    Role: 'Sr Eng 2',
    Reports_To: 'Sneha Reddy',
    Mentor_Name: 'Sneha Reddy',
    Client: 'NXP',
    Project_Type: 'Pattern Debug',
    Smartest_V7: 8, Smartest_V8: 7,
    Test_Program_Integration: 7, Test_Program_Development: 8, Pattern_Debugs: 9,
    Scripting_Tools: 7, Data_Analytics: 7, Version_Control_Git: 8, IP_Knowledge: 7,
    Post_Silicon_Validation: 7, Bench_Setup_Stabilization: 7, Loadboard_Bringup: 7,
    HW_Validation: 7, GRR_Analysis: 7,
    Engineering_Bringups: 7, Multisite_Bringup: 7, TapeOut_To_HVM: 7,
    Volume_KPI_Analysis: 6, Production_Release_Track: 7,
    Is_Independent: true, Does_Automation_Scripting: true, Handles_1_on_1_Mentoring: true,
    Produces_Documentation: true, Runs_Classroom_Training: true,
    Manages_Project_Deliverables: false, Manages_Multiple_Clients: false,
  },
  {
    Employee_Name: 'Ananya Krishnan',
    Role: 'Sr Eng 1',
    Reports_To: 'Sneha Reddy',
    Mentor_Name: 'Karthik Iyer',
    Client: 'NXP',
    Project_Type: 'Lab Bringup',
    Smartest_V7: 7, Smartest_V8: 7,
    Test_Program_Integration: 7, Test_Program_Development: 7, Pattern_Debugs: 7,
    Scripting_Tools: 7, Data_Analytics: 6, Version_Control_Git: 7, IP_Knowledge: 6,
    Post_Silicon_Validation: 8, Bench_Setup_Stabilization: 9, Loadboard_Bringup: 8,
    HW_Validation: 7, GRR_Analysis: 8,
    Engineering_Bringups: 7, Multisite_Bringup: 6, TapeOut_To_HVM: 6,
    Volume_KPI_Analysis: 6, Production_Release_Track: 6,
    Is_Independent: true, Does_Automation_Scripting: true, Handles_1_on_1_Mentoring: true,
    Produces_Documentation: true, Runs_Classroom_Training: false,
    Manages_Project_Deliverables: false, Manages_Multiple_Clients: false,
  },
  {
    Employee_Name: 'Rahul Desai',
    Role: 'Eng 2',
    Reports_To: 'Karthik Iyer',
    Mentor_Name: 'Ananya Krishnan',
    Client: 'NXP',
    Project_Type: 'Test Development',
    Smartest_V7: 6, Smartest_V8: 6,
    Test_Program_Integration: 6, Test_Program_Development: 7, Pattern_Debugs: 6,
    Scripting_Tools: 7, Data_Analytics: 6, Version_Control_Git: 7, IP_Knowledge: 5,
    Post_Silicon_Validation: 6, Bench_Setup_Stabilization: 6, Loadboard_Bringup: 6,
    HW_Validation: 6, GRR_Analysis: 5,
    Engineering_Bringups: 6, Multisite_Bringup: 5, TapeOut_To_HVM: 5,
    Volume_KPI_Analysis: 5, Production_Release_Track: 5,
    Is_Independent: true, Does_Automation_Scripting: true, Handles_1_on_1_Mentoring: false,
    Produces_Documentation: false, Runs_Classroom_Training: false,
    Manages_Project_Deliverables: false, Manages_Multiple_Clients: false,
  },
  {
    Employee_Name: 'Meera Joshi',
    Role: 'Eng 1',
    Reports_To: 'Karthik Iyer',
    Mentor_Name: 'Rahul Desai',
    Client: 'Infineon',
    Project_Type: 'Characterization',
    Smartest_V7: 5, Smartest_V8: 5,
    Test_Program_Integration: 5, Test_Program_Development: 5, Pattern_Debugs: 5,
    Scripting_Tools: 5, Data_Analytics: 5, Version_Control_Git: 6, IP_Knowledge: 4,
    Post_Silicon_Validation: 5, Bench_Setup_Stabilization: 5, Loadboard_Bringup: 5,
    HW_Validation: 5, GRR_Analysis: 5,
    Engineering_Bringups: 5, Multisite_Bringup: 4, TapeOut_To_HVM: 4,
    Volume_KPI_Analysis: 4, Production_Release_Track: 4,
    Is_Independent: true, Does_Automation_Scripting: false, Handles_1_on_1_Mentoring: false,
    Produces_Documentation: false, Runs_Classroom_Training: false,
    Manages_Project_Deliverables: false, Manages_Multiple_Clients: false,
  },
  {
    Employee_Name: 'Vikram Rao',
    Role: 'Eng 2',
    Reports_To: 'Sneha Reddy',
    Mentor_Name: 'Sneha Reddy',
    Client: 'Infineon',
    Project_Type: 'Automation',
    Smartest_V7: 4, Smartest_V8: 3,
    Test_Program_Integration: 6, Test_Program_Development: 6, Pattern_Debugs: 6,
    Scripting_Tools: 8, Data_Analytics: 7, Version_Control_Git: 8, IP_Knowledge: 5,
    Post_Silicon_Validation: 8, Bench_Setup_Stabilization: 9, Loadboard_Bringup: 8,
    HW_Validation: 7, GRR_Analysis: 8,
    Engineering_Bringups: 6, Multisite_Bringup: 5, TapeOut_To_HVM: 5,
    Volume_KPI_Analysis: 6, Production_Release_Track: 5,
    Is_Independent: true, Does_Automation_Scripting: true, Handles_1_on_1_Mentoring: false,
    Produces_Documentation: true, Runs_Classroom_Training: false,
    Manages_Project_Deliverables: false, Manages_Multiple_Clients: false,
  },
  {
    Employee_Name: 'Divya Patel',
    Role: 'Sr Eng 1',
    Reports_To: 'Arjun Mehta',
    Mentor_Name: 'Arjun Mehta',
    Client: 'Broadcom',
    Project_Type: 'HVM Support',
    Smartest_V7: 7, Smartest_V8: 6,
    Test_Program_Integration: 7, Test_Program_Development: 6, Pattern_Debugs: 6,
    Scripting_Tools: 6, Data_Analytics: 7, Version_Control_Git: 7, IP_Knowledge: 6,
    Post_Silicon_Validation: 6, Bench_Setup_Stabilization: 6, Loadboard_Bringup: 6,
    HW_Validation: 6, GRR_Analysis: 6,
    Engineering_Bringups: 7, Multisite_Bringup: 6, TapeOut_To_HVM: 7,
    Volume_KPI_Analysis: 7, Production_Release_Track: 7,
    Is_Independent: true, Does_Automation_Scripting: false, Handles_1_on_1_Mentoring: false,
    Produces_Documentation: false, Runs_Classroom_Training: false,
    Manages_Project_Deliverables: false, Manages_Multiple_Clients: false,
  },
  {
    Employee_Name: 'Nikhil Sharma',
    Role: 'Lead',
    Reports_To: 'Priya Nair',
    Mentor_Name: 'Priya Nair',
    Client: 'Broadcom',
    Project_Type: 'New Product Intro',
    Smartest_V7: 8, Smartest_V8: 9,
    Test_Program_Integration: 8, Test_Program_Development: 8, Pattern_Debugs: 7,
    Scripting_Tools: 8, Data_Analytics: 8, Version_Control_Git: 8, IP_Knowledge: 7,
    Post_Silicon_Validation: 7, Bench_Setup_Stabilization: 7, Loadboard_Bringup: 8,
    HW_Validation: 8, GRR_Analysis: 7,
    Engineering_Bringups: 8, Multisite_Bringup: 8, TapeOut_To_HVM: 8,
    Volume_KPI_Analysis: 8, Production_Release_Track: 8,
    Is_Independent: true, Does_Automation_Scripting: true, Handles_1_on_1_Mentoring: true,
    Produces_Documentation: true, Runs_Classroom_Training: true,
    Manages_Project_Deliverables: false, Manages_Multiple_Clients: false,
  },
  {
    Employee_Name: 'Lakshmi Venkat',
    Role: 'Eng 1',
    Reports_To: 'Nikhil Sharma',
    Mentor_Name: 'Nikhil Sharma',
    Client: 'Broadcom',
    Project_Type: 'Test Development',
    Smartest_V7: 4, Smartest_V8: 4,
    Test_Program_Integration: 4, Test_Program_Development: 4, Pattern_Debugs: 4,
    Scripting_Tools: 4, Data_Analytics: 4, Version_Control_Git: 5, IP_Knowledge: 3,
    Post_Silicon_Validation: 4, Bench_Setup_Stabilization: 4, Loadboard_Bringup: 4,
    HW_Validation: 4, GRR_Analysis: 3,
    Engineering_Bringups: 4, Multisite_Bringup: 3, TapeOut_To_HVM: 3,
    Volume_KPI_Analysis: 3, Production_Release_Track: 3,
    Is_Independent: false, Does_Automation_Scripting: false, Handles_1_on_1_Mentoring: false,
    Produces_Documentation: false, Runs_Classroom_Training: false,
    Manages_Project_Deliverables: false, Manages_Multiple_Clients: false,
  },
  {
    Employee_Name: 'Aditya Menon',
    Role: 'Intern',
    Reports_To: 'Rahul Desai',
    Mentor_Name: 'Meera Joshi',
    Client: 'Infineon',
    Project_Type: 'Lab Support',
    Smartest_V7: 3, Smartest_V8: 3,
    Test_Program_Integration: 3, Test_Program_Development: 3, Pattern_Debugs: 3,
    Scripting_Tools: 4, Data_Analytics: 4, Version_Control_Git: 5, IP_Knowledge: 2,
    Post_Silicon_Validation: 4, Bench_Setup_Stabilization: 5, Loadboard_Bringup: 4,
    HW_Validation: 3, GRR_Analysis: 3,
    Engineering_Bringups: 3, Multisite_Bringup: 2, TapeOut_To_HVM: 2,
    Volume_KPI_Analysis: 2, Production_Release_Track: 2,
    Is_Independent: false, Does_Automation_Scripting: false, Handles_1_on_1_Mentoring: false,
    Produces_Documentation: false, Runs_Classroom_Training: false,
    Manages_Project_Deliverables: false, Manages_Multiple_Clients: false,
  },
  {
    Employee_Name: 'Pooja Banerjee',
    Role: 'Sr Eng 2',
    Reports_To: 'Nikhil Sharma',
    Mentor_Name: 'Nikhil Sharma',
    Client: 'Qualcomm',
    Project_Type: 'Multisite Bringup',
    Smartest_V7: 8, Smartest_V8: 8,
    Test_Program_Integration: 8, Test_Program_Development: 7, Pattern_Debugs: 8,
    Scripting_Tools: 7, Data_Analytics: 7, Version_Control_Git: 8, IP_Knowledge: 7,
    Post_Silicon_Validation: 8, Bench_Setup_Stabilization: 8, Loadboard_Bringup: 9,
    HW_Validation: 8, GRR_Analysis: 8,
    Engineering_Bringups: 8, Multisite_Bringup: 9, TapeOut_To_HVM: 8,
    Volume_KPI_Analysis: 7, Production_Release_Track: 7,
    Is_Independent: true, Does_Automation_Scripting: true, Handles_1_on_1_Mentoring: true,
    Produces_Documentation: true, Runs_Classroom_Training: false,
    Manages_Project_Deliverables: false, Manages_Multiple_Clients: false,
  },
  {
    Employee_Name: 'Suresh Kumar',
    Role: 'Staff',
    Reports_To: '',
    Mentor_Name: '',
    Client: 'NXP',
    Project_Type: 'Cross-Client Strategy',
    Smartest_V7: 9, Smartest_V8: 9,
    Test_Program_Integration: 9, Test_Program_Development: 9, Pattern_Debugs: 8,
    Scripting_Tools: 8, Data_Analytics: 9, Version_Control_Git: 9, IP_Knowledge: 9,
    Post_Silicon_Validation: 8, Bench_Setup_Stabilization: 8, Loadboard_Bringup: 8,
    HW_Validation: 9, GRR_Analysis: 8,
    Engineering_Bringups: 9, Multisite_Bringup: 8, TapeOut_To_HVM: 9,
    Volume_KPI_Analysis: 9, Production_Release_Track: 9,
    Is_Independent: true, Does_Automation_Scripting: true, Handles_1_on_1_Mentoring: true,
    Produces_Documentation: true, Runs_Classroom_Training: true,
    Manages_Project_Deliverables: true, Manages_Multiple_Clients: true,
  },
  {
    Employee_Name: 'Ishita Gupta',
    Role: 'Eng 1',
    Reports_To: 'Pooja Banerjee',
    Mentor_Name: 'Pooja Banerjee',
    Client: 'Qualcomm',
    Project_Type: 'GRR Analysis',
    Smartest_V7: 5, Smartest_V8: 6,
    Test_Program_Integration: 5, Test_Program_Development: 5, Pattern_Debugs: 5,
    Scripting_Tools: 6, Data_Analytics: 6, Version_Control_Git: 6, IP_Knowledge: 4,
    Post_Silicon_Validation: 6, Bench_Setup_Stabilization: 6, Loadboard_Bringup: 5,
    HW_Validation: 5, GRR_Analysis: 7,
    Engineering_Bringups: 5, Multisite_Bringup: 4, TapeOut_To_HVM: 4,
    Volume_KPI_Analysis: 5, Production_Release_Track: 4,
    Is_Independent: true, Does_Automation_Scripting: false, Handles_1_on_1_Mentoring: false,
    Produces_Documentation: false, Runs_Classroom_Training: false,
    Manages_Project_Deliverables: false, Manages_Multiple_Clients: false,
  },
]

function boolToCsv(value) {
  return value ? 'TRUE' : 'FALSE'
}

/** Build a valid 15-row sample CSV string matching the required schema. */
export function generateSampleCsvString() {
  const data = SAMPLE_ROWS.map((row) => {
    const out = {}
    for (const col of REQUIRED_COLUMNS) {
      const val = row[col]
      out[col] = typeof val === 'boolean' ? boolToCsv(val) : val
    }
    return out
  })
  return Papa.unparse(data, { columns: REQUIRED_COLUMNS })
}

/** Trigger a browser download of the sample CSV. */
export function downloadSampleCsv() {
  const csv = generateSampleCsvString()
  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' })
  const url = URL.createObjectURL(blob)
  const anchor = document.createElement('a')
  anchor.href = url
  anchor.download = 'sample_team_roster.csv'
  document.body.appendChild(anchor)
  anchor.click()
  document.body.removeChild(anchor)
  URL.revokeObjectURL(url)
}
