import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'
import { REQUIRED_COLUMNS } from '../src/utils/csvSchema.js'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const root = path.resolve(__dirname, '..')

/** Fixed hierarchy from product plan; skills vary for demo RAG spread. */
const PEOPLE = [
  {
    Employee_Name: 'Rajmohan',
    Role: 'Manager',
    Reports_To: '',
    Mentor_Name: '',
    Client: 'Client Q',
    Project_Type: 'Multi-Client Oversight',
    SMT_Versions_Known: 'Both',
    Other_Testers: true,
    SC_Experience: true,
    SOD_Handling: true,
    CONT_Status: 'Bringup',
    DBD_Bringup: true,
    Product_Focus: 'Both',
    IP_Debug_Level: 'Advanced',
    Client_Demand: 'High',
    Project_Projections_Current: true,
    TML_Scripting: 8,
    CS_ES_HVM_Releases: 9,
    Is_Independent: true,
    Does_Automation_Scripting: true,
    Handles_1_on_1_Mentoring: true,
    Produces_Documentation: true,
    Runs_Classroom_Training: true,
    Manages_Project_Deliverables: true,
    Manages_Multiple_Clients: true,
  },
  {
    Employee_Name: 'Bhanu',
    Role: 'Lead',
    Reports_To: 'Rajmohan',
    Mentor_Name: 'Rajmohan',
    Client: 'Client Q',
    Project_Type: 'HVM Support',
    SMT_Versions_Known: '8',
    Other_Testers: true,
    SC_Experience: true,
    SOD_Handling: true,
    CONT_Status: 'Bringup',
    DBD_Bringup: true,
    Product_Focus: 'Both',
    IP_Debug_Level: 'Advanced',
    Client_Demand: 'High',
    Project_Projections_Current: true,
    TML_Scripting: 8,
    CS_ES_HVM_Releases: 8,
    Is_Independent: true,
    Does_Automation_Scripting: true,
    Handles_1_on_1_Mentoring: true,
    Produces_Documentation: true,
    Runs_Classroom_Training: true,
    Manages_Project_Deliverables: true,
    Manages_Multiple_Clients: false,
  },
  {
    Employee_Name: 'Mari',
    Role: 'Lead',
    Reports_To: 'Rajmohan',
    Mentor_Name: 'Rajmohan',
    Client: 'Client A',
    Project_Type: 'NPI',
    SMT_Versions_Known: '8',
    Other_Testers: true,
    SC_Experience: true,
    SOD_Handling: false,
    CONT_Status: 'Debug',
    DBD_Bringup: true,
    Product_Focus: 'NPI',
    IP_Debug_Level: 'Advanced',
    Client_Demand: 'Medium',
    Project_Projections_Current: true,
    TML_Scripting: 7,
    CS_ES_HVM_Releases: 7,
    Is_Independent: true,
    Does_Automation_Scripting: true,
    Handles_1_on_1_Mentoring: true,
    Produces_Documentation: true,
    Runs_Classroom_Training: false,
    Manages_Project_Deliverables: true,
    Manages_Multiple_Clients: false,
  },
  {
    Employee_Name: 'Sriram',
    Role: 'Lead',
    Reports_To: 'Rajmohan',
    Mentor_Name: 'Rajmohan',
    Client: 'Client G',
    Project_Type: 'Sustaining',
    SMT_Versions_Known: '7',
    Other_Testers: true,
    SC_Experience: true,
    SOD_Handling: true,
    CONT_Status: 'Bringup',
    DBD_Bringup: false,
    Product_Focus: 'Sustaining',
    IP_Debug_Level: 'Basic',
    Client_Demand: 'Medium',
    Project_Projections_Current: true,
    TML_Scripting: 7,
    CS_ES_HVM_Releases: 6,
    Is_Independent: true,
    Does_Automation_Scripting: true,
    Handles_1_on_1_Mentoring: true,
    Produces_Documentation: true,
    Runs_Classroom_Training: false,
    Manages_Project_Deliverables: true,
    Manages_Multiple_Clients: false,
  },
  {
    Employee_Name: 'Siva',
    Role: 'Sr Eng 2',
    Reports_To: 'Rajmohan',
    Mentor_Name: 'Rajmohan',
    Client: 'Client A',
    Project_Type: 'Platform Mentoring',
    SMT_Versions_Known: 'Both',
    Other_Testers: true,
    SC_Experience: true,
    SOD_Handling: true,
    CONT_Status: 'Bringup',
    DBD_Bringup: true,
    Product_Focus: 'Both',
    IP_Debug_Level: 'Advanced',
    Client_Demand: 'High',
    Project_Projections_Current: true,
    TML_Scripting: 9,
    CS_ES_HVM_Releases: 8,
    Is_Independent: true,
    Does_Automation_Scripting: true,
    Handles_1_on_1_Mentoring: true,
    Produces_Documentation: true,
    Runs_Classroom_Training: true,
    Manages_Project_Deliverables: false,
    Manages_Multiple_Clients: false,
  },
  {
    Employee_Name: 'Hussain',
    Role: 'Sr Eng 1',
    Reports_To: 'Bhanu',
    Mentor_Name: 'Bhanu',
    Client: 'Client Q',
    Project_Type: 'WS',
    SMT_Versions_Known: '7',
    Other_Testers: true,
    SC_Experience: true,
    SOD_Handling: false,
    CONT_Status: 'Debug',
    DBD_Bringup: true,
    Product_Focus: 'Sustaining',
    IP_Debug_Level: 'Basic',
    Client_Demand: 'High',
    Project_Projections_Current: true,
    TML_Scripting: 7,
    CS_ES_HVM_Releases: 6,
    Is_Independent: true,
    Does_Automation_Scripting: true,
    Handles_1_on_1_Mentoring: true,
    Produces_Documentation: true,
    Runs_Classroom_Training: false,
    Manages_Project_Deliverables: false,
    Manages_Multiple_Clients: false,
  },
  {
    Employee_Name: 'Sneha',
    Role: 'Sr Eng 1',
    Reports_To: 'Bhanu',
    Mentor_Name: 'Siva',
    Client: 'Client Q',
    Project_Type: 'FT',
    SMT_Versions_Known: '7',
    Other_Testers: true,
    SC_Experience: false,
    SOD_Handling: true,
    CONT_Status: 'Bringup',
    DBD_Bringup: true,
    Product_Focus: 'NPI',
    IP_Debug_Level: 'Advanced',
    Client_Demand: 'Medium',
    Project_Projections_Current: true,
    TML_Scripting: 6,
    CS_ES_HVM_Releases: 7,
    Is_Independent: true,
    Does_Automation_Scripting: true,
    Handles_1_on_1_Mentoring: true,
    Produces_Documentation: true,
    Runs_Classroom_Training: false,
    Manages_Project_Deliverables: false,
    Manages_Multiple_Clients: false,
  },
  {
    Employee_Name: 'Jayaram',
    Role: 'Sr Eng 1',
    Reports_To: 'Bhanu',
    Mentor_Name: 'Bhanu',
    Client: 'Client A',
    Project_Type: 'DBD',
    SMT_Versions_Known: '7',
    Other_Testers: false,
    SC_Experience: true,
    SOD_Handling: false,
    CONT_Status: 'Debug',
    DBD_Bringup: true,
    Product_Focus: 'Sustaining',
    IP_Debug_Level: 'Basic',
    Client_Demand: 'Medium',
    Project_Projections_Current: false,
    TML_Scripting: 6,
    CS_ES_HVM_Releases: 5,
    Is_Independent: true,
    Does_Automation_Scripting: false,
    Handles_1_on_1_Mentoring: false,
    Produces_Documentation: false,
    Runs_Classroom_Training: false,
    Manages_Project_Deliverables: false,
    Manages_Multiple_Clients: false,
  },
  {
    Employee_Name: 'Sunil',
    Role: 'Sr Eng 1',
    Reports_To: 'Mari',
    Mentor_Name: 'Mari',
    Client: 'Client A',
    Project_Type: 'NPI',
    SMT_Versions_Known: '7',
    Other_Testers: true,
    SC_Experience: true,
    SOD_Handling: true,
    CONT_Status: 'Bringup',
    DBD_Bringup: false,
    Product_Focus: 'NPI',
    IP_Debug_Level: 'Basic',
    Client_Demand: 'Medium',
    Project_Projections_Current: true,
    TML_Scripting: 7,
    CS_ES_HVM_Releases: 6,
    Is_Independent: true,
    Does_Automation_Scripting: true,
    Handles_1_on_1_Mentoring: true,
    Produces_Documentation: true,
    Runs_Classroom_Training: false,
    Manages_Project_Deliverables: false,
    Manages_Multiple_Clients: false,
  },
  {
    Employee_Name: 'Kevin',
    Role: 'Sr Eng 1',
    Reports_To: 'Mari',
    Mentor_Name: 'Mari',
    Client: 'Client A',
    Project_Type: 'CONT',
    SMT_Versions_Known: '7',
    Other_Testers: false,
    SC_Experience: false,
    SOD_Handling: true,
    CONT_Status: 'Debug',
    DBD_Bringup: true,
    Product_Focus: 'Both',
    IP_Debug_Level: 'Basic',
    Client_Demand: 'Low',
    Project_Projections_Current: true,
    TML_Scripting: 5,
    CS_ES_HVM_Releases: 5,
    Is_Independent: true,
    Does_Automation_Scripting: true,
    Handles_1_on_1_Mentoring: false,
    Produces_Documentation: true,
    Runs_Classroom_Training: false,
    Manages_Project_Deliverables: false,
    Manages_Multiple_Clients: false,
  },
  {
    Employee_Name: 'Abarna',
    Role: 'Sr Eng 1',
    Reports_To: 'Sriram',
    Mentor_Name: 'Sriram',
    Client: 'Client G',
    Project_Type: 'Training / Sustaining',
    SMT_Versions_Known: '7',
    Other_Testers: true,
    SC_Experience: true,
    SOD_Handling: false,
    CONT_Status: 'Bringup',
    DBD_Bringup: true,
    Product_Focus: 'Sustaining',
    IP_Debug_Level: 'Advanced',
    Client_Demand: 'Medium',
    Project_Projections_Current: true,
    TML_Scripting: 7,
    CS_ES_HVM_Releases: 6,
    Is_Independent: true,
    Does_Automation_Scripting: true,
    Handles_1_on_1_Mentoring: true,
    Produces_Documentation: true,
    Runs_Classroom_Training: true,
    Manages_Project_Deliverables: false,
    Manages_Multiple_Clients: false,
  },
  {
    Employee_Name: 'Abi',
    Role: 'Eng 1',
    Reports_To: 'Hussain',
    Mentor_Name: 'Siva',
    Client: 'Client Q',
    Project_Type: 'Lab Support',
    SMT_Versions_Known: '7',
    Other_Testers: false,
    SC_Experience: true,
    SOD_Handling: false,
    CONT_Status: 'Debug',
    DBD_Bringup: false,
    Product_Focus: 'Sustaining',
    IP_Debug_Level: 'Basic',
    Client_Demand: 'Medium',
    Project_Projections_Current: true,
    TML_Scripting: 5,
    CS_ES_HVM_Releases: 4,
    Is_Independent: true,
    Does_Automation_Scripting: false,
    Handles_1_on_1_Mentoring: false,
    Produces_Documentation: false,
    Runs_Classroom_Training: false,
    Manages_Project_Deliverables: false,
    Manages_Multiple_Clients: false,
  },
  {
    Employee_Name: 'Sai',
    Role: 'Eng 1',
    Reports_To: 'Sneha',
    Mentor_Name: 'Siva',
    Client: 'Client Q',
    Project_Type: 'Pattern Support',
    SMT_Versions_Known: '7',
    Other_Testers: false,
    SC_Experience: false,
    SOD_Handling: true,
    CONT_Status: 'No_Idea',
    DBD_Bringup: false,
    Product_Focus: 'NPI',
    IP_Debug_Level: 'None',
    Client_Demand: 'Low',
    Project_Projections_Current: false,
    TML_Scripting: 4,
    CS_ES_HVM_Releases: 3,
    Is_Independent: false,
    Does_Automation_Scripting: false,
    Handles_1_on_1_Mentoring: false,
    Produces_Documentation: false,
    Runs_Classroom_Training: false,
    Manages_Project_Deliverables: false,
    Manages_Multiple_Clients: false,
  },
  {
    Employee_Name: 'Santhosh',
    Role: 'Eng 2',
    Reports_To: 'Sriram',
    Mentor_Name: 'Sneha',
    Client: 'Client G',
    Project_Type: 'Scripting',
    SMT_Versions_Known: '7',
    Other_Testers: false,
    SC_Experience: true,
    SOD_Handling: true,
    CONT_Status: 'Debug',
    DBD_Bringup: true,
    Product_Focus: 'Sustaining',
    IP_Debug_Level: 'Basic',
    Client_Demand: 'Medium',
    Project_Projections_Current: true,
    TML_Scripting: 8,
    CS_ES_HVM_Releases: 5,
    Is_Independent: true,
    Does_Automation_Scripting: true,
    Handles_1_on_1_Mentoring: false,
    Produces_Documentation: false,
    Runs_Classroom_Training: false,
    Manages_Project_Deliverables: false,
    Manages_Multiple_Clients: false,
  },
  {
    Employee_Name: 'Vijay',
    Role: 'Eng 2',
    Reports_To: 'Siva',
    Mentor_Name: 'Siva',
    Client: 'Client A',
    Project_Type: 'Bringup',
    SMT_Versions_Known: '7',
    Other_Testers: false,
    SC_Experience: true,
    SOD_Handling: false,
    CONT_Status: 'Bringup',
    DBD_Bringup: true,
    Product_Focus: 'NPI',
    IP_Debug_Level: 'Basic',
    Client_Demand: 'Medium',
    Project_Projections_Current: true,
    TML_Scripting: 6,
    CS_ES_HVM_Releases: 5,
    Is_Independent: true,
    Does_Automation_Scripting: true,
    Handles_1_on_1_Mentoring: false,
    Produces_Documentation: false,
    Runs_Classroom_Training: false,
    Manages_Project_Deliverables: false,
    Manages_Multiple_Clients: false,
  },
  {
    Employee_Name: 'Ankush',
    Role: 'Eng 1',
    Reports_To: 'Sriram',
    Mentor_Name: 'Sriram',
    Client: 'Client G',
    Project_Type: 'Support',
    SMT_Versions_Known: '7',
    Other_Testers: false,
    SC_Experience: false,
    SOD_Handling: false,
    CONT_Status: 'No_Idea',
    DBD_Bringup: false,
    Product_Focus: 'Sustaining',
    IP_Debug_Level: 'None',
    Client_Demand: 'Low',
    Project_Projections_Current: false,
    TML_Scripting: 3,
    CS_ES_HVM_Releases: 2,
    Is_Independent: false,
    Does_Automation_Scripting: false,
    Handles_1_on_1_Mentoring: false,
    Produces_Documentation: false,
    Runs_Classroom_Training: false,
    Manages_Project_Deliverables: false,
    Manages_Multiple_Clients: false,
  },
  {
    Employee_Name: 'Bhavya',
    Role: 'Intern',
    Reports_To: 'Sriram',
    Mentor_Name: 'Abarna',
    Client: 'Client G',
    Project_Type: 'Learning Track',
    SMT_Versions_Known: '7',
    Other_Testers: false,
    SC_Experience: false,
    SOD_Handling: false,
    CONT_Status: 'No_Idea',
    DBD_Bringup: false,
    Product_Focus: 'NPI',
    IP_Debug_Level: 'None',
    Client_Demand: 'Low',
    Project_Projections_Current: false,
    TML_Scripting: 2,
    CS_ES_HVM_Releases: 1,
    Is_Independent: false,
    Does_Automation_Scripting: false,
    Handles_1_on_1_Mentoring: false,
    Produces_Documentation: false,
    Runs_Classroom_Training: false,
    Manages_Project_Deliverables: false,
    Manages_Multiple_Clients: false,
  },
]

function esc(v) {
  const s = String(v)
  return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s
}

function bool(v) {
  return v ? 'TRUE' : 'FALSE'
}

const BOOL_COLS = new Set([
  'Other_Testers',
  'SC_Experience',
  'SOD_Handling',
  'DBD_Bringup',
  'Project_Projections_Current',
  'Is_Independent',
  'Does_Automation_Scripting',
  'Handles_1_on_1_Mentoring',
  'Produces_Documentation',
  'Runs_Classroom_Training',
  'Manages_Project_Deliverables',
  'Manages_Multiple_Clients',
])

const lines = [REQUIRED_COLUMNS.join(',')]
for (const row of PEOPLE) {
  lines.push(
    REQUIRED_COLUMNS.map((c) =>
      BOOL_COLS.has(c) ? bool(row[c]) : esc(row[c] ?? ''),
    ).join(','),
  )
}
const csv = `${lines.join('\n')}\n`

for (const target of [
  path.join(root, 'sample', 'sample_team_roster.csv'),
  path.join(root, 'public', 'sample', 'sample_team_roster.csv'),
]) {
  fs.mkdirSync(path.dirname(target), { recursive: true })
  fs.writeFileSync(target, csv, 'utf8')
}

console.log(`Wrote ${PEOPLE.length} rows to sample/ and public/sample/`)
