import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'
import {
  BOOLEAN_COLUMNS,
  CSV_OUTPUT_COLUMNS,
} from '../src/utils/csvSchema.js'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const root = path.resolve(__dirname, '..')

/**
 * 17-person demo roster.
 * Rules: Product_Focus NPI|Sustaining; Project_Type WS|FT|Both (NPI → WS|FT only).
 * Tuned for ~60% GREEN / 30% AMBER / 10% RED after RAG + hierarchy.
 */
const PEOPLE = [
  {
    Employee_Name: 'Rajmohan',
    Role: 'Manager',
    Reports_To: '',
    Mentor_Name: '',
    Client: 'Client Q',
    Project_Type: 'Both',
    Allocation_Status: 'Project',
    Billing_Months_Remaining: 12,
    Upcoming_Commitment: 'Multi-client Q3 review',
    SMT_7_Known: true,
    SMT_8_Known: true,
    Other_Testers: true,
    SC_Experience: true,
    SOD_Handling: true,
    CONT_Status: 'Bringup',
    DBD_Bringup: true,
    Product_Focus: 'Sustaining',
    IP_Debug_Level: 'Advanced',
    Client_Demand: 'High',
    Project_Projections_Current: true,
    TML_Scripting: 8,
    CS_ES_HVM_Releases: 9,
    Is_Independent: true,
    Does_Automation_Scripting: true,
    Handles_1_on_1_Mentoring: true,
    Produces_Documentation: true,
    Runs_Classroom_Training: true,
    Manages_Project_Deliverables: true,
    Manages_Multiple_Clients: true,
  },
  {
    Employee_Name: 'Bhanu',
    Role: 'Lead',
    Reports_To: 'Rajmohan',
    Mentor_Name: 'Rajmohan',
    Client: 'Client Q',
    Project_Type: 'Both',
    Allocation_Status: 'Project',
    Billing_Months_Remaining: 9,
    Upcoming_Commitment: 'Client Q HVM ramp',
    SMT_7_Known: true,
    SMT_8_Known: true,
    Other_Testers: true,
    SC_Experience: true,
    SOD_Handling: true,
    CONT_Status: 'Bringup',
    DBD_Bringup: true,
    Product_Focus: 'Sustaining',
    IP_Debug_Level: 'Advanced',
    Client_Demand: 'High',
    Project_Projections_Current: true,
    TML_Scripting: 8,
    CS_ES_HVM_Releases: 8,
    Is_Independent: true,
    Does_Automation_Scripting: true,
    Handles_1_on_1_Mentoring: true,
    Produces_Documentation: true,
    Runs_Classroom_Training: true,
    Manages_Project_Deliverables: true,
    Manages_Multiple_Clients: false,
  },
  {
    Employee_Name: 'Mari',
    Role: 'Lead',
    Reports_To: 'Rajmohan',
    Mentor_Name: 'Rajmohan',
    Client: 'Client A',
    Project_Type: 'FT',
    Allocation_Status: 'Project',
    Billing_Months_Remaining: 7,
    Upcoming_Commitment: 'Client A NPI tapeout',
    SMT_7_Known: true,
    SMT_8_Known: true,
    Other_Testers: true,
    SC_Experience: true,
    SOD_Handling: true,
    CONT_Status: 'Bringup',
    DBD_Bringup: true,
    Product_Focus: 'NPI',
    IP_Debug_Level: 'Advanced',
    Client_Demand: 'High',
    Project_Projections_Current: true,
    TML_Scripting: 8,
    CS_ES_HVM_Releases: 8,
    Is_Independent: true,
    Does_Automation_Scripting: true,
    Handles_1_on_1_Mentoring: true,
    Produces_Documentation: true,
    Runs_Classroom_Training: true,
    Manages_Project_Deliverables: true,
    Manages_Multiple_Clients: false,
  },
  {
    Employee_Name: 'Sriram',
    Role: 'Lead',
    Reports_To: 'Rajmohan',
    Mentor_Name: 'Rajmohan',
    Client: 'Client G',
    Project_Type: 'WS',
    Allocation_Status: 'Project',
    Billing_Months_Remaining: 6,
    Upcoming_Commitment: 'Client G sustaining',
    SMT_7_Known: true,
    SMT_8_Known: true,
    Other_Testers: true,
    SC_Experience: true,
    SOD_Handling: true,
    CONT_Status: 'Bringup',
    DBD_Bringup: true,
    Product_Focus: 'Sustaining',
    IP_Debug_Level: 'Advanced',
    Client_Demand: 'Medium',
    Project_Projections_Current: true,
    TML_Scripting: 8,
    CS_ES_HVM_Releases: 7,
    Is_Independent: true,
    Does_Automation_Scripting: true,
    Handles_1_on_1_Mentoring: true,
    Produces_Documentation: true,
    Runs_Classroom_Training: true,
    Manages_Project_Deliverables: true,
    Manages_Multiple_Clients: false,
  },
  {
    Employee_Name: 'Siva',
    Role: 'Sr Eng 2',
    Reports_To: 'Rajmohan',
    Mentor_Name: 'Rajmohan',
    Client: 'Client A',
    Project_Type: 'Both',
    Allocation_Status: 'Project',
    Billing_Months_Remaining: 10,
    Upcoming_Commitment: 'Platform mentoring pool',
    SMT_7_Known: true,
    SMT_8_Known: true,
    Other_Testers: true,
    SC_Experience: true,
    SOD_Handling: true,
    CONT_Status: 'Bringup',
    DBD_Bringup: true,
    Product_Focus: 'Sustaining',
    IP_Debug_Level: 'Advanced',
    Client_Demand: 'High',
    Project_Projections_Current: true,
    TML_Scripting: 9,
    CS_ES_HVM_Releases: 8,
    Is_Independent: true,
    Does_Automation_Scripting: true,
    Handles_1_on_1_Mentoring: true,
    Produces_Documentation: true,
    Runs_Classroom_Training: true,
    Manages_Project_Deliverables: false,
    Manages_Multiple_Clients: false,
  },
  {
    Employee_Name: 'Hussain',
    Role: 'Sr Eng 1',
    Reports_To: 'Bhanu',
    Mentor_Name: 'Bhanu',
    Client: 'Client Q',
    Project_Type: 'WS',
    Allocation_Status: 'Project',
    Billing_Months_Remaining: 8,
    Upcoming_Commitment: 'Client Q WS bringup',
    SMT_7_Known: true,
    SMT_8_Known: true,
    Other_Testers: true,
    SC_Experience: true,
    SOD_Handling: true,
    CONT_Status: 'Bringup',
    DBD_Bringup: true,
    Product_Focus: 'Sustaining',
    IP_Debug_Level: 'Advanced',
    Client_Demand: 'High',
    Project_Projections_Current: true,
    TML_Scripting: 8,
    CS_ES_HVM_Releases: 7,
    Is_Independent: true,
    Does_Automation_Scripting: true,
    Handles_1_on_1_Mentoring: true,
    Produces_Documentation: true,
    Runs_Classroom_Training: false,
    Manages_Project_Deliverables: false,
    Manages_Multiple_Clients: false,
  },
  {
    Employee_Name: 'Sneha',
    Role: 'Sr Eng 1',
    Reports_To: 'Bhanu',
    Mentor_Name: 'Siva',
    Client: 'Client Q',
    Project_Type: 'FT',
    Allocation_Status: 'Project',
    Billing_Months_Remaining: 5,
    Upcoming_Commitment: 'Client Q FT debug',
    SMT_7_Known: true,
    SMT_8_Known: true,
    Other_Testers: true,
    SC_Experience: true,
    SOD_Handling: true,
    CONT_Status: 'Bringup',
    DBD_Bringup: true,
    Product_Focus: 'NPI',
    IP_Debug_Level: 'Advanced',
    Client_Demand: 'Medium',
    Project_Projections_Current: true,
    TML_Scripting: 7,
    CS_ES_HVM_Releases: 7,
    Is_Independent: true,
    Does_Automation_Scripting: true,
    Handles_1_on_1_Mentoring: true,
    Produces_Documentation: true,
    Runs_Classroom_Training: false,
    Manages_Project_Deliverables: false,
    Manages_Multiple_Clients: false,
  },
  {
    Employee_Name: 'Karthik',
    Role: 'Eng 2',
    Reports_To: 'Mari',
    Mentor_Name: 'Mari',
    Client: 'Client A',
    Project_Type: 'WS',
    Allocation_Status: 'Project',
    Billing_Months_Remaining: 6,
    Upcoming_Commitment: 'Client A WS NPI',
    SMT_7_Known: true,
    SMT_8_Known: true,
    Other_Testers: true,
    SC_Experience: true,
    SOD_Handling: true,
    CONT_Status: 'Bringup',
    DBD_Bringup: true,
    Product_Focus: 'NPI',
    IP_Debug_Level: 'Basic',
    Client_Demand: 'Medium',
    Project_Projections_Current: true,
    TML_Scripting: 7,
    CS_ES_HVM_Releases: 6,
    Is_Independent: true,
    Does_Automation_Scripting: true,
    Handles_1_on_1_Mentoring: false,
    Produces_Documentation: false,
    Runs_Classroom_Training: false,
    Manages_Project_Deliverables: false,
    Manages_Multiple_Clients: false,
  },
  {
    Employee_Name: 'Priya',
    Role: 'Eng 2',
    Reports_To: 'Sriram',
    Mentor_Name: 'Sriram',
    Client: 'Client G',
    Project_Type: 'Both',
    Allocation_Status: 'Project',
    Billing_Months_Remaining: 7,
    Upcoming_Commitment: 'Client G dual track',
    SMT_7_Known: true,
    SMT_8_Known: true,
    Other_Testers: true,
    SC_Experience: true,
    SOD_Handling: true,
    CONT_Status: 'Bringup',
    DBD_Bringup: true,
    Product_Focus: 'Sustaining',
    IP_Debug_Level: 'Basic',
    Client_Demand: 'Medium',
    Project_Projections_Current: true,
    TML_Scripting: 7,
    CS_ES_HVM_Releases: 6,
    Is_Independent: true,
    Does_Automation_Scripting: true,
    Handles_1_on_1_Mentoring: false,
    Produces_Documentation: false,
    Runs_Classroom_Training: false,
    Manages_Project_Deliverables: false,
    Manages_Multiple_Clients: false,
  },
  {
    Employee_Name: 'Arun',
    Role: 'Eng 1',
    Reports_To: 'Mari',
    Mentor_Name: 'Karthik',
    Client: 'Client A',
    Project_Type: 'FT',
    Allocation_Status: 'Project',
    Billing_Months_Remaining: 4,
    Upcoming_Commitment: 'Client A FT support',
    SMT_7_Known: true,
    SMT_8_Known: false,
    Other_Testers: true,
    SC_Experience: true,
    SOD_Handling: false,
    CONT_Status: 'Debug',
    DBD_Bringup: true,
    Product_Focus: 'NPI',
    IP_Debug_Level: 'Basic',
    Client_Demand: 'Medium',
    Project_Projections_Current: true,
    TML_Scripting: 6,
    CS_ES_HVM_Releases: 5,
    Is_Independent: true,
    Does_Automation_Scripting: false,
    Handles_1_on_1_Mentoring: false,
    Produces_Documentation: false,
    Runs_Classroom_Training: false,
    Manages_Project_Deliverables: false,
    Manages_Multiple_Clients: false,
  },
  // --- AMBER (watch): missing a responsibility or borderline ---
  {
    Employee_Name: 'Deepak',
    Role: 'Eng 2',
    Reports_To: 'Bhanu',
    Mentor_Name: 'Hussain',
    Client: 'Client Q',
    Project_Type: 'WS',
    Allocation_Status: 'Project',
    Billing_Months_Remaining: 3,
    Upcoming_Commitment: 'Client Q pattern',
    SMT_7_Known: true,
    SMT_8_Known: true,
    Other_Testers: true,
    SC_Experience: true,
    SOD_Handling: true,
    CONT_Status: 'Bringup',
    DBD_Bringup: true,
    Product_Focus: 'Sustaining',
    IP_Debug_Level: 'Basic',
    Client_Demand: 'Medium',
    Project_Projections_Current: true,
    TML_Scripting: 6,
    CS_ES_HVM_Releases: 6,
    Is_Independent: true,
    Does_Automation_Scripting: true,
    Handles_1_on_1_Mentoring: false,
    Produces_Documentation: false,
    Runs_Classroom_Training: false,
    Manages_Project_Deliverables: false,
    Manages_Multiple_Clients: false,
  },
  {
    Employee_Name: 'Nisha',
    Role: 'Sr Eng 1',
    Reports_To: 'Sriram',
    Mentor_Name: 'Siva',
    Client: 'Client G',
    Project_Type: 'FT',
    Allocation_Status: 'Project',
    Billing_Months_Remaining: 5,
    Upcoming_Commitment: 'Client G FT',
    SMT_7_Known: true,
    SMT_8_Known: true,
    Other_Testers: true,
    SC_Experience: true,
    SOD_Handling: true,
    CONT_Status: 'Bringup',
    DBD_Bringup: true,
    Product_Focus: 'Sustaining',
    IP_Debug_Level: 'Advanced',
    Client_Demand: 'High',
    Project_Projections_Current: true,
    TML_Scripting: 7,
    CS_ES_HVM_Releases: 7,
    Is_Independent: true,
    Does_Automation_Scripting: true,
    Handles_1_on_1_Mentoring: true,
    Produces_Documentation: false,
    Runs_Classroom_Training: false,
    Manages_Project_Deliverables: false,
    Manages_Multiple_Clients: false,
  },
  {
    Employee_Name: 'Vikram',
    Role: 'Eng 1',
    Reports_To: 'Sriram',
    Mentor_Name: 'Priya',
    Client: 'Client G',
    Project_Type: 'WS',
    Allocation_Status: 'Bench',
    Billing_Months_Remaining: 1,
    Upcoming_Commitment: '',
    SMT_7_Known: true,
    SMT_8_Known: false,
    Other_Testers: false,
    SC_Experience: true,
    SOD_Handling: false,
    CONT_Status: 'Debug',
    DBD_Bringup: true,
    Product_Focus: 'Sustaining',
    IP_Debug_Level: 'Basic',
    Client_Demand: 'Low',
    Project_Projections_Current: false,
    TML_Scripting: 5,
    CS_ES_HVM_Releases: 4,
    Is_Independent: false,
    Does_Automation_Scripting: false,
    Handles_1_on_1_Mentoring: false,
    Produces_Documentation: false,
    Runs_Classroom_Training: false,
    Manages_Project_Deliverables: false,
    Manages_Multiple_Clients: false,
  },
  {
    Employee_Name: 'Meera',
    Role: 'Eng 2',
    Reports_To: 'Mari',
    Mentor_Name: 'Mari',
    Client: 'Client A',
    Project_Type: 'FT',
    Allocation_Status: 'Project',
    Billing_Months_Remaining: 4,
    Upcoming_Commitment: 'Client A script',
    SMT_7_Known: true,
    SMT_8_Known: true,
    Other_Testers: true,
    SC_Experience: true,
    SOD_Handling: true,
    CONT_Status: 'Bringup',
    DBD_Bringup: true,
    Product_Focus: 'NPI',
    IP_Debug_Level: 'Basic',
    Client_Demand: 'Medium',
    Project_Projections_Current: true,
    TML_Scripting: 6,
    CS_ES_HVM_Releases: 6,
    Is_Independent: true,
    Does_Automation_Scripting: true,
    Handles_1_on_1_Mentoring: false,
    Produces_Documentation: false,
    Runs_Classroom_Training: false,
    Manages_Project_Deliverables: false,
    Manages_Multiple_Clients: false,
  },
  {
    Employee_Name: 'Santhosh',
    Role: 'Eng 1',
    Reports_To: 'Sriram',
    Mentor_Name: 'Hussain',
    Client: 'Client Q',
    Project_Type: 'Both',
    Allocation_Status: 'Project',
    Billing_Months_Remaining: 6,
    Upcoming_Commitment: 'Client Q dual',
    SMT_7_Known: true,
    SMT_8_Known: false,
    Other_Testers: true,
    SC_Experience: true,
    SOD_Handling: false,
    CONT_Status: 'Bringup',
    DBD_Bringup: true,
    Product_Focus: 'Sustaining',
    IP_Debug_Level: 'Basic',
    Client_Demand: 'Medium',
    Project_Projections_Current: true,
    TML_Scripting: 5,
    CS_ES_HVM_Releases: 5,
    Is_Independent: false,
    Does_Automation_Scripting: false,
    Handles_1_on_1_Mentoring: false,
    Produces_Documentation: false,
    Runs_Classroom_Training: false,
    Manages_Project_Deliverables: false,
    Manages_Multiple_Clients: false,
  },
  // --- RED (at risk): weak scores / many failed checks ---
  {
    Employee_Name: 'Ravi',
    Role: 'Eng 2',
    Reports_To: 'Sriram',
    Mentor_Name: 'Priya',
    Client: 'Client G',
    Project_Type: 'FT',
    Allocation_Status: 'Bench',
    Billing_Months_Remaining: 0,
    Upcoming_Commitment: '',
    SMT_7_Known: false,
    SMT_8_Known: false,
    Other_Testers: false,
    SC_Experience: false,
    SOD_Handling: false,
    CONT_Status: 'No_Idea',
    DBD_Bringup: false,
    Product_Focus: 'Sustaining',
    IP_Debug_Level: 'None',
    Client_Demand: 'Low',
    Project_Projections_Current: false,
    TML_Scripting: 2,
    CS_ES_HVM_Releases: 1,
    Is_Independent: false,
    Does_Automation_Scripting: false,
    Handles_1_on_1_Mentoring: false,
    Produces_Documentation: false,
    Runs_Classroom_Training: false,
    Manages_Project_Deliverables: false,
    Manages_Multiple_Clients: false,
  },
  {
    Employee_Name: 'Ananya',
    Role: 'Intern',
    Reports_To: 'Rajmohan',
    Mentor_Name: 'Karthik',
    Client: 'Client A',
    Project_Type: 'WS',
    Allocation_Status: 'Project',
    Billing_Months_Remaining: 2,
    Upcoming_Commitment: 'Learning track',
    SMT_7_Known: false,
    SMT_8_Known: false,
    Other_Testers: false,
    SC_Experience: false,
    SOD_Handling: false,
    CONT_Status: 'No_Idea',
    DBD_Bringup: false,
    Product_Focus: 'NPI',
    IP_Debug_Level: 'None',
    Client_Demand: 'Low',
    Project_Projections_Current: false,
    TML_Scripting: 1,
    CS_ES_HVM_Releases: 1,
    Is_Independent: false,
    Does_Automation_Scripting: false,
    Handles_1_on_1_Mentoring: false,
    Produces_Documentation: false,
    Runs_Classroom_Training: false,
    Manages_Project_Deliverables: false,
    Manages_Multiple_Clients: false,
  },
]

function esc(v) {
  const s = String(v)
  return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s
}

function bool(v) {
  return v ? 'TRUE' : 'FALSE'
}

const BOOL_COLS = new Set([...BOOLEAN_COLUMNS, 'Is_Departed'])

const lines = [CSV_OUTPUT_COLUMNS.join(',')]
for (const row of PEOPLE) {
  lines.push(
    CSV_OUTPUT_COLUMNS.map((c) => {
      if (c === 'Is_Departed') return bool(false)
      return BOOL_COLS.has(c) ? bool(row[c]) : esc(row[c] ?? '')
    }).join(','),
  )
}
const csv = `${lines.join('\n')}\n`

for (const target of [
  path.join(root, 'sample', 'sample_team_roster.csv'),
  path.join(root, 'public', 'sample', 'sample_team_roster.csv'),
]) {
  fs.mkdirSync(path.dirname(target), { recursive: true })
  fs.writeFileSync(target, csv, 'utf8')
}

const generatedPath = path.join(root, 'src', 'utils', 'sampleCsv.generated.js')
fs.writeFileSync(
  generatedPath,
  `/** Auto-generated by scripts/generateSampleRoster.mjs — do not edit. */\nexport const SAMPLE_CSV_TEXT = ${JSON.stringify(csv)}\n`,
  'utf8',
)

console.log(
  `Wrote ${PEOPLE.length} rows to sample/, public/sample/, and sampleCsv.generated.js`,
)
